"""add exercise detection tables

Revision ID: 475f22fd4538
Revises: a8979090266c
Create Date: 2025-12-09 10:32:39.299943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '475f22fd4538'
down_revision: Union[str, None] = 'a8979090266c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_detections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('sport', sa.String(length=50), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_detections_id'), 'exercise_detections', ['id'], unique=False)
    op.create_index(op.f('ix_exercise_detections_name'), 'exercise_detections', ['name'], unique=True)
    op.create_table('exercise_angle_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('angle_name', sa.String(length=50), nullable=False),
    sa.Column('min_angle', sa.Float(), nullable=False),
    sa.Column('max_angle', sa.Float(), nullable=False),
    sa.Column('phase', sa.String(length=20), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise_detections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_angle_rules_id'), 'exercise_angle_rules', ['id'], unique=False)
    op.create_table('exercise_scoring_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('angle_name', sa.String(length=50), nullable=False),
    sa.Column('excellent_min', sa.Float(), nullable=False),
    sa.Column('excellent_max', sa.Float(), nullable=False),
    sa.Column('good_min', sa.Float(), nullable=False),
    sa.Column('good_max', sa.Float(), nullable=False),
    sa.Column('acceptable_min', sa.Float(), nullable=False),
    sa.Column('acceptable_max', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise_detections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_scoring_rules_id'), 'exercise_scoring_rules', ['id'], unique=False)
    op.create_table('exercise_tips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('score_min', sa.Integer(), nullable=True),
    sa.Column('score_max', sa.Integer(), nullable=True),
    sa.Column('tip_text', sa.String(length=255), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise_detections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_tips_id'), 'exercise_tips', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exercise_tips_id'), table_name='exercise_tips')
    op.drop_table('exercise_tips')
    op.drop_index(op.f('ix_exercise_scoring_rules_id'), table_name='exercise_scoring_rules')
    op.drop_table('exercise_scoring_rules')
    op.drop_index(op.f('ix_exercise_angle_rules_id'), table_name='exercise_angle_rules')
    op.drop_table('exercise_angle_rules')
    op.drop_index(op.f('ix_exercise_detections_name'), table_name='exercise_detections')
    op.drop_index(op.f('ix_exercise_detections_id'), table_name='exercise_detections')
    op.drop_table('exercise_detections')
    # ### end Alembic commands ###