"""add activities and daily stats

Revision ID: a8979090266c
Revises: 
Create Date: 2025-12-04 23:57:04.986874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a8979090266c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.Enum('EXERCISE', 'MEAL', 'WATER', 'MOOD', 'SLEEP', 'WELLNESS', name='activitytype'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('points_earned', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('protein', sa.Float(), nullable=True),
    sa.Column('carbs', sa.Float(), nullable=True),
    sa.Column('fat', sa.Float(), nullable=True),
    sa.Column('water_glasses', sa.Integer(), nullable=True),
    sa.Column('mood_level', sa.String(length=50), nullable=True),
    sa.Column('sleep_hours', sa.Float(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_id'), 'activities', ['id'], unique=False)
    op.create_table('daily_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=True),
    sa.Column('exercise_points', sa.Integer(), nullable=True),
    sa.Column('nutrition_points', sa.Integer(), nullable=True),
    sa.Column('wellness_points', sa.Integer(), nullable=True),
    sa.Column('exercises_completed', sa.Integer(), nullable=True),
    sa.Column('meals_logged', sa.Integer(), nullable=True),
    sa.Column('water_glasses', sa.Integer(), nullable=True),
    sa.Column('total_calories', sa.Integer(), nullable=True),
    sa.Column('total_protein', sa.Float(), nullable=True),
    sa.Column('total_carbs', sa.Float(), nullable=True),
    sa.Column('total_fat', sa.Float(), nullable=True),
    sa.Column('mood', sa.String(length=50), nullable=True),
    sa.Column('sleep_hours', sa.Float(), nullable=True),
    sa.Column('wellness_activities', sa.Integer(), nullable=True),
    sa.Column('streak_maintained', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_stats_id'), 'daily_stats', ['id'], unique=False)
    op.add_column('users', sa.Column('level', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('total_exercises', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('total_meals_logged', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('total_water_glasses', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('total_wellness_activities', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('last_activity', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               nullable=True)
    op.alter_column('users', 'birth_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'total_points',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'current_streak',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'longest_streak',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
    op.alter_column('users', 'last_login',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.alter_column('users', 'last_login',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('users', 'longest_streak',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'current_streak',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'total_points',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'birth_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('users', 'full_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'last_activity')
    op.drop_column('users', 'total_wellness_activities')
    op.drop_column('users', 'total_water_glasses')
    op.drop_column('users', 'total_meals_logged')
    op.drop_column('users', 'total_exercises')
    op.drop_column('users', 'level')
    op.drop_index(op.f('ix_daily_stats_id'), table_name='daily_stats')
    op.drop_table('daily_stats')
    op.drop_index(op.f('ix_activities_id'), table_name='activities')
    op.drop_table('activities')
    # ### end Alembic commands ###